### ISSUE TITLE
nebula-conosle container failure in ARM docker env

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docker-compose#134]
In ARM server or Docker Desktop of macOS with Apple Chip, the current console container will fail to run due to it's x86 arch only.

The fix is https://github.com/vesoft-inc/nebula-console/pull/189 .

Before that, one mitigation could be to add `platform: linux/amd64` for console container like:

```yaml
  console:
    image: vesoft/nebula-console:nightly
    # this line------------
    platform: linux/amd64
    # this line------------
    entrypoint: ""
    command: 
      - sh
      - -c
      - |
        for i in `seq 1 60`;do
          var=`nebula-console -addr graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "storaged0":9779,"storaged1":9779,"storaged2":9779'`;
          if [[ $$? == 0 ]];then
            break;
          fi;
          sleep 1;
          echo "retry to add hosts.";
        done && tail -f /dev/null;
    depends_on:
      - graphd
    networks:
      - nebula-net
```
