### ISSUE TITLE
Namespace parameter for charts may not be needed.

### ISSUE THREAD

**Issue by matrixji** [vesoft-inc/nebula-docker-compose#70]
目前正在使用这里提供的helm chart尝试做部署，发现namespace定义成了一个变量，但是之前的习惯都是通过 helm 的 --namespace 来指定。
关于namespace定义的最佳实践的讨论，可以参考： https://github.com/helm/helm/issues/5465

建议不要使用参数定义namespace，可以参考下面的两种方式：

1. 使用 **{{ .Release.Namespace }}**：
``` yaml
# In templates/*.yaml 
metadata: 
    namespace: {{ .Release.Namespace }}
```

2. 或者干脆不定义：
```yaml
# In templates/*.yaml
metadata: 
```
